#!/usr/bin/env bash

function git_setup {
  git config --global user.email "travis@travis-ci.org"
  git config --global user.name "Travis CI"
  git remote remove origin
  git remote add origin-travis https://${GH_TOKEN}@github.com/CFI-UL/scoreboard.git > /dev/null 2>&1
  git checkout master
}

function git_push {
  git push --quiet --set-upstream origin-travis master
}

function update_data_and_commit {
  ./bin/scoreboard update
  git diff
  git add --all
  git commit --message "Travis CI update data. [ci skip]"
}

function build_app_and_commit {
  npm run build
  git add --all
  git commit --message "Travis CI build. [ci skip]"
}

if [ $TRAVIS_BRANCH='master' ]; then
  if [ $TRAVIS_EVENT_TYPE='cron' ]; then
    git_setup
    update_data_and_commit
    git_push
  elif [ $TRAVIS_EVENT_TYPE='push' ] then
    git_setup
    update_data_and_commit
    build_app_and_commit
    git_push
  fi
fi
