#!/usr/bin/env bash

if [ $TRAVIS_BRANCH='master' ]; then
  if [ $TRAVIS_EVENT_TYPE='push' ] && [ $TRAVIS_EVENT_TYPE='cron' ]; then

    git config --global user.email "travis@travis-ci.org"
    git config --global user.name "Travis CI"

    ./bin/update-data update
    git add .
    git commit --message "Travis CI update data. [ci skip]"

    git remote remove origin
    git remote add origin https://${GH_TOKEN}@github.com/CFI-UL/scoreboard.git > /dev/null 2>&1
    git push origin master
  fi
fi
